In [1]:
import torch

In [2]:
x=torch.empty(5,3)

In [3]:
x

tensor([[0.0000e+00, 2.0000e+00, 0.0000e+00],
        [2.0000e+00, 1.4569e-19, 2.7517e+12],
        [7.5338e+28, 3.0313e+32, 6.3828e+28],
        [1.4603e-19, 1.0899e+27, 6.8943e+34],
        [1.1835e+22, 7.0976e+22, 1.8515e+28]])

In [4]:
x=torch.rand(5,3)

In [5]:
x

tensor([[0.1669, 0.4546, 0.1888],
        [0.0287, 0.1538, 0.7172],
        [0.9217, 0.9040, 0.0689],
        [0.9694, 0.6257, 0.8387],
        [0.4706, 0.5125, 0.5646]])

In [6]:
x=torch.zeros(5,3)

In [7]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [8]:
x=torch.tensor([5.5,3])

In [12]:
x

tensor([5.5000, 3.0000])